Rails.application.routes.draw do
  match('sections', {:via => :get, :to => 'sections#index'})
  match('sections/new', {:via => :get, :to => 'sections#new'})
  match('sections', {:via => :post, :to => 'sections#create'})
  match('sections/:id', {:via => :get, :to => 'sections#show'})
  match('sections/:id/edit', {:via => :get, :to => 'sections#edit'})
  match('sections/:id/edit', {:via => [:patch, :put], :to => 'sections#update'})
  match('sections/:id/delete', {:via => :get, :to => 'sections#delete'})
  match('sections/:id', {:via => :delete, :to => 'sections#destroy'})
  match('sections/:id/next', {:via => :get, :to => 'sections#next'})
  match('sections/:id/previous', {:via => :get, :to => 'sections#previous'})
  match('lessons', {:via => :get, :to => 'lessons#index'})
  match('lessons/new', {:via => :get, :to => 'lessons#new'})
  match('lessons/destroy', {:via => :get, :to => 'lessons#destroy'})
  match('lessons', {:via => :post, :to => 'lessons#create'})
  match('lessons/:id', {:via => :get, :to => 'lessons#show'})
  match('lessons/:id/edit', {:via => :get, :to => 'lessons#edit'})
  match('lessons/:id/edit', {:via => [:patch, :put], :to => 'lessons#update'})
  match('lessons/:id/delete', {:via => :get, :to => 'lessons#delete'})
  match('lessons/:id', {:via => :delete, :to => 'lessons#destroy'})
  match('lessons/:id/next', {:via => :get, :to => 'lessons#next'})
  match('lessons/:id/previous', {:via => :get, :to => 'lessons#previous'})
end
